language: c
sudo: false # only for faster builds
env:
  global:
    - CODECOV_TOKEN=:uuid-repo-token
    
script:
  - gcc -Wall -fprofile-arcs -ftest-coverage hello.c -o hello
  - ./hello
  - gcov hello.c

after_success:
  - bash <(curl -s https://codecov.io/bash)
